name: Platform Racing 4 Client
run-name: ${{ github.actor }} is building a new version of Platform Racing 4 Client 🚀
on: [push]
jobs:
  export-web:
    name: Export Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image
        run: |
          cd client
          docker build -t pr4 --file docker/web.dockerfile .
          if [ "$GITHUB_REF_NAME" = "main" ]; then
            tag="$(date +%F-%H-%M)-$GITHUB_REF_NAME-$GITHUB_SHA"
            docker tag pr4 ghcr.io/platform-racing-4/client/web:latest
            docker push ghcr.io/platform-racing-4/client/web:latest
            docker tag pr4 ghcr.io/platform-racing-4/client/web:$tag
            docker push ghcr.io/platform-racing-4/client/web:$tag
          fi
