services:

  dev-web:
    image: ghcr.io/jacob-grahn/platform-racing-4-client-web:#CLIENT_WEB_TAG
    restart: always
  
  dev-api:
    image: ghcr.io/jacob-grahn/platform-racing-4-api:#API_TAG
    restart: always