services:
  caddy:
    restart: always
    volumes:
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    image: caddy:2.5.2-alpine
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    environment:
      CONFIG_VERSION: 1 # update this number for force caddy to restart and read new config

volumes:
  caddy-data: